### ISSUE TITLE
ember-cli-babel deprecation

### ISSUE THREAD

**Issue by Techn1x** [StevenHeinrich/ember-leaflet-draw#11]
Have started getting these deprecation warnings when building ember
```
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: fsm-webapp -> ember-leaflet-draw -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: fsm-webapp -> ember-leaflet-draw -> ember-composability-tools -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: fsm-webapp -> ember-leaflet-draw -> ember-composability-tools -> ember-getowner-polyfill -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: fsm-webapp -> ember-leaflet-draw -> ember-composability-tools -> ember-wormhole -> ember-cli-babel
```

Looks like it's due to this addon's references to old versions of ember-cli-babel and ember-composability-tools.

@StevenHeinrich If you don't have time for this addon anymore I'd be happy to take on some of the maintenance required (updating packages + merging PRs) if you give me access + npm publish permission. Up to you though.

**Comment by StevenHeinrich** [comment]
@Techn1x I welcome the help. I am a bit crunched right now. You can submit a PR and we can get that in fast. If you want npm publishing access to be more involved, I can grant that as well... if I had your npm username.

**Comment by Techn1x** [comment]
sorry - changed jobs shortly after and didn't need this anymore
